### ISSUE TITLE
how to save DDQN model

### ISSUE THREAD

**Issue by yesungkeke** [Albert-Z-Guo/Deep-Reinforcement-Stock-Trading#11]
Hi! Thank you for your last answer!
Recently I try to train the DDQN in your project,so I write" if model_name == 'DDQN':
                                                                                              agent.model.save('saved_models/DDQN_ep' + str(e) + '.h5')" 

But when I try to run "evaluate" the project reminded me "SavedModel file does not exist ".
I found that in DDQN.py there should be a file named"DDQN_target.h5". So could you tell me how to write exact code to save the model?
Thank you very much!!!

**Comment by Albert-Z-Guo** [comment]
Hi there, thanks for reaching out!
`train.py` saves trained models (line 142-143); you can modify model file names there.
`evaluate.py` uses saved models to backtest; you can pass in modified model file names through the input arguments.
Input arguments example can be found in README.md.

**Comment by yesungkeke** [comment]
Hi! Thank you for your  answering!
I know what you mean,but my problem is that  I modify model file names there like 
        if model_name == 'DDQN':
            agent.model.save('saved_models/DDQN_ep' + str(e) + '.h5')
but the evaluate.py needs two files,one is"DDQN_ep10.h5", another is "DDQN_ep10_target.h5". I don't know how  to save the "DDQN_ep10_target.h5",I can only save "DDQN_ep10.h5".
Hope you can answer me Sincerely!
