### ISSUE TITLE
Evaluate.py custom window_size gives error

### ISSUE THREAD

**Issue by fengints** [Albert-Z-Guo/Deep-Reinforcement-Stock-Trading#19]
Evaluate.py custom window_size gives error

**Comment by fengints** [comment]
#20 This fixes the error

**Comment by Albert-Z-Guo** [comment]
Hi @fengints, many thanks for fixing this error! 

This project was a toy project when I was learning deep reinforcement learning myself. For better framework and closer to real world trading applications, I'd recommend trying this repository: https://github.com/AI4Finance-Foundation/FinRL

Happy to chat more if you are interested.

Cheers,
Albert

**Comment by fengints** [comment]
Thanks, project you sent looks good.
I also found this one, at first glance this looks clean and easy to use.
https://github.com/trality/fire

**Comment by fengints** [comment]
If you are still supporting your toy project, converting model to float16/bfloat16 would be good idea to decrease training time. I tried myself, but i'm encountering overflow errors.
