### ISSUE TITLE
Why don't save critic model weight on DDPG?

### ISSUE THREAD

**Issue by chingchou888** [Albert-Z-Guo/Deep-Reinforcement-Stock-Trading#2]
Hi, Albert

Could you tell me why don't save critic model weight on DDPG ?

**Comment by Albert-Z-Guo** [comment]
Hi @chingchou888, thanks for pointing this out! I have fixed this problem. I also added 1/buffer_size factor in the step to calculate of sampled policy gradient and simplified the evaluation pipeline arguments. Let me know if you find another bug!
