### ISSUE TITLE
The paper according to this repository

### ISSUE THREAD

**Issue by TonyZhang-sjtu** [Albert-Z-Guo/Deep-Reinforcement-Stock-Trading#25]
Is there any paper corresponding to this code repository that we can further refer? Thanks very much!

**Comment by TonyZhang-sjtu** [comment]
What's more, it always takes about one hour and a half to train one epoch on Mac CPU, and there is 10 epochs! Furthermore, the speed is gradually decreasing as it may take at least 15GB memory in later stage of training, but the raw data is only about 500KB, what makes that? I have attempted to train DQN on GPU, but the tensorflow and keras structure does not suppory it in some key processes. Has anybody encountered with the same situation and any suggestions? Thanks！

**Comment by erdult** [comment]
same here. the code is too slow

**Comment by Albert-Z-Guo** [comment]
Hi @TonyZhang-sjtu and @erdult,

Thanks for reaching out!

This project was a toy project when I was learning deep reinforcement learning myself. For better framework (with paper reference) and closer to real world trading applications, I'd recommend trying this repository: https://github.com/AI4Finance-Foundation/FinRL

Cheers,
Albert
